const legacyRoomBoot=roomBoot;
const legacyPairCard=pairCard;
const SOLO_AROMAS={zitrus_grapefruit:'Zitrone & Grapefruit',apfel_birne:'Apfel & Birne',pfirsich_aprikose:'Pfirsich & Aprikose',exotische_fruechte:'Ananas, Maracuja & Exotik',bluete_holunder:'Weiße Blüten & Holunder',kraeuter_gras:'Kräuter & frisches Gras',mandel_nuss:'Mandel & Nuss',hefe_brot:'Hefe & Brioche',honig_vanille:'Honig & Vanille',feuerstein_mineral:'Feuerstein & Mineralik'};
let soloAns=blank(),soloState=null;
function isWhiteType(t){return t==='white_solo'||t==='white_simple'||t==='white'}
function pairCard(r){const s=getSession(r.code),phase=r.phase==='tasting'?'Freie Verkostung':r.phase==='profiles'?'Profile offen':'Aufgelöst',white=isWhiteType(r.tasting_type);return `<section class="card pair ${white?'whitepair':'redpair'}"><div class="pairtop"><div><div class="ey">${white?'🥂 Weißwein':'🍷 Rotwein'}</div><h3>${e(r.theme)}</h3></div><span class="pill">${phase}</span></div><p class="muted small">${e(r.intro||'')}</p><a class="btn ${s?'secondary':'primary'} full center" href="?event=${encodeURIComponent(E)}&room=${encodeURIComponent(r.code)}${KIOSK?'&kiosk=1':''}">${s?'Weiter':'Starten'}</a></section>`}
async function roomBoot(){clearPoll();const S=getSession(R);try{st=await rpc('get_public_state',{p_code:R,p_token:S?.token||null})}catch{return legacyRoomBoot()}if(st.tasting_type==='white_solo')return soloBoot(S);if(st.tasting_type==='white_simple')return whiteSimpleBoot(S);return legacyRoomBoot()}
function soloPick(k,label){return `<div class="ttl">${label}</div><div class="grid">${[1,2,3,4,5].map(v=>`<button class="choice ${soloAns[k]===v?'on':''}" data-solo-k="${k}" data-v="${v}">${v}</button>`).join('')}</div>`}
function soloAromas(){return `<div class="ttl">Aromarichtungen – 2 bis 4 auswählen</div><div class="grid two aroma-grid">${Object.entries(SOLO_AROMAS).map(([id,label])=>`<button class="choice ${soloAns.aromas.includes(id)?'on':''}" data-solo-a="${id}">${label}</button>`).join('')}</div><p class="small muted">${soloAns.aromas.length}/4 gewählt</p>`}
function soloComplete(){return ['nose_intensity','oak','body','tannin','acidity','freshness','finish','finish_intensity'].every(k=>soloAns[k])&&soloAns.aromas.length>=2&&soloAns.aromas.length<=4}
async function soloBoot(S){clearPoll();if(!S||!st.me){const n=getName();if(!n)return joinRoom();try{const d=await rpc('join_tasting',{p_code:R,p_name:n});setSession(R,{token:d.token,name:d.name});return soloBoot(getSession(R))}catch(x){return xRoom(x.message)}}soloState=await rpc('solo_get_state',{p_code:R,p_token:S.token});if(soloState.phase==='revealed')return soloReveal();soloAns=await rpc('solo_get_answer',{p_code:R,p_token:S.token}).catch(()=>blank());soloAns={...blank(),...soloAns,aromas:soloAns.aromas||[]};if(soloState.me.guess_submitted)return soloWaiting();return soloTaste()}
function soloTaste(){const done=soloComplete();A.innerHTML=brand(`<span class="room">${e(soloState.theme||R)}</span>`)+`<div class="toprow">${backLink()}</div><section class="card tasting"><div class="sectiontitle"><span>🥂</span><div><b>Deinen Weißwein bewerten</b><p class="muted small">Die Auflösung bleibt bis zur Host-Freigabe gesperrt.</p></div></div>${soloPick('nose_intensity','Duft- & Fruchtintensität')}${soloAromas()}${soloPick('oak','Schmelz & Cremigkeit')}${soloPick('body','Körper & Fülle')}${soloPick('tannin','Süße-Eindruck · 1 knochentrocken, 5 deutlich süß')}${soloPick('acidity','Frische & Säurespannung')}${soloPick('finish','Länge & Intensität des Abgangs')}<div class="field"><label>Eine Beobachtung <span class="muted small">(optional)</span></label><input id="solo-note" maxlength="180" value="${e(soloAns.note||'')}"></div></section><section class="card compact">${done?'<b>✓ Verkostung vollständig</b><button id="solo-guesses" class="btn primary full">Zu den Schätzfragen</button>':'<b>Noch nicht vollständig</b>'}</section>`;document.querySelectorAll('[data-solo-k]').forEach(x=>x.onclick=()=>{soloAns[x.dataset.soloK]=+x.dataset.v;soloSave();soloTaste()});document.querySelectorAll('[data-solo-a]').forEach(x=>x.onclick=()=>{const id=x.dataset.soloA,a=soloAns.aromas;soloAns.aromas=a.includes(id)?a.filter(v=>v!==id):a.length<4?[...a,id]:a;soloSave();soloTaste()});const note=document.getElementById('solo-note');if(note)note.oninput=x=>{soloAns.note=x.target.value;soloSave()};const go=document.getElementById('solo-guesses');if(go)go.onclick=()=>soloGuesses()}
async function soloSave(){const S=getSession(R);await rpc('solo_save_answer',{p_code:R,p_token:S.token,p_payload:soloAns}).catch(x=>toast(x.message))}
function soloGuesses(){const opts={grape:['Sauvignon Blanc','Chardonnay','Riesling','Petit Courbu/Petit Manseng'],region:['Loire','Burgund','Elsass','Südwestfrankreich'],price:['unter 10 €','10–20 €','20–30 €','über 30 €']},g={};const block=(k,l)=>`<div class="ttl">${l}</div><div class="grid two">${opts[k].map(v=>`<button class="choice" data-solo-g="${k}" data-v="${e(v)}">${e(v)}</button>`).join('')}</div>`;A.innerHTML=brand()+`<div class="toprow">${backLink()}</div><section class="card"><h2>Drei Schätzfragen</h2>${block('grape','Rebsorte')}${block('region','Region')}${block('price','Preisklasse')}<button id="solo-send" class="btn primary full">Antworten speichern</button></section>`;document.querySelectorAll('[data-solo-g]').forEach(x=>x.onclick=()=>{g[x.dataset.soloG]=x.dataset.v;x.parentElement.querySelectorAll('.choice').forEach(y=>y.classList.remove('on'));x.classList.add('on')});const send=document.getElementById('solo-send');send.onclick=async()=>{if(!g.grape||!g.region||!g.price)return toast('Bitte alle drei Fragen beantworten');send.disabled=true;try{await rpc('solo_save_guesses',{p_code:R,p_token:getSession(R).token,p_grape:g.grape,p_region:g.region,p_price:g.price});soloWaiting()}catch(x){send.disabled=false;toast(x.message||'Speichern fehlgeschlagen')}}}
function soloWaiting(){A.innerHTML=brand()+`<section class="card wait"><h2>Antworten gespeichert</h2><p class="muted">Die Auflösung erscheint, sobald der Host sie freigibt.</p></section>`;poll=setInterval(async()=>{const x=await rpc('solo_get_state',{p_code:R,p_token:getSession(R).token});if(x.phase==='revealed')roomBoot()},4000)}
async function soloReveal(){clearPoll();const r=await rpc('solo_get_reveal',{p_code:R,p_token:getSession(R).token});const me=r.leaderboard.find(x=>x.name===getSession(R).name);A.innerHTML=brand()+`<div class="toprow">${backLink()}</div><section class="card hero revealhero"><h2>${me?`${e(me.name)}: ${me.score}/${me.max_score} Punkte`:'Auflösung'}</h2></section><section class="card"><h3>${e(r.wine.name)} ${e(r.wine.vintage||'')}</h3><p class="muted">${e(r.wine.details?.summary||'')}</p><p>${e(r.wine.details?.dossier||'')}</p><p><b>Servieren:</b> ${e(r.wine.details?.serve||'')}</p></section><section class="card"><h3>Leaderboard</h3>${roomRanks(r.leaderboard)}</section>`}
async function whiteSimpleBoot(S){clearPoll();if(!S||!st.me){const n=getName();if(!n)return joinRoom();const d=await rpc('join_tasting',{p_code:R,p_name:n});setSession(R,{token:d.token,name:d.name});return whiteSimpleBoot(getSession(R))}if(st.phase==='revealed')return reveal();const rows=await rpc('get_my_answers',{p_code:R,p_token:S.token});ans={1:blank(),2:blank()};rows.forEach(x=>ans[x.glass_no]={...blank(),...x,aromas:x.aromas||[]});if(st.me.guess_submitted)return waitReveal();whiteSimpleTaste()}
function wsPick(k,label){return `<div class="ttl">${label}</div><div class="grid">${[1,2,3,4,5].map(v=>`<button class="choice ${ans[g][k]===v?'on':''}" data-ws-k="${k}" data-v="${v}">${v}</button>`).join('')}</div>`}
function wsComplete(gl){const a=ans[gl];return ['nose_intensity','oak','body','tannin','acidity','freshness','finish','finish_intensity'].every(k=>a[k])&&a.aromas.length>=2&&a.aromas.length<=4}
function wsForm(){const ar=`<div class="ttl">Aromarichtungen – 2 bis 4 auswählen</div><div class="grid two aroma-grid">${Object.entries(SOLO_AROMAS).map(([id,label])=>`<button class="choice ${ans[g].aromas.includes(id)?'on':''}" data-ws-a="${id}">${label}</button>`).join('')}</div><p class="small muted">${ans[g].aromas.length}/4 gewählt</p>`;return `<div class="sectiontitle"><span>🥂</span><div><b>Weißwein bewerten</b></div></div>${wsPick('nose_intensity','Duft- & Fruchtintensität')}${ar}${wsPick('oak','Schmelz & Cremigkeit')}${wsPick('body','Körper & Fülle')}${wsPick('tannin','Süße-Eindruck · 1 knochentrocken, 5 deutlich süß')}${wsPick('acidity','Säure · 1 mild, 5 sehr hoch')}${wsPick('freshness','Frische · 1 matt, 5 sehr frisch')}${wsPick('finish','Länge des Abgangs · 1 kurz, 5 sehr lang')}${wsPick('finish_intensity','Intensität des Abgangs · 1 kaum, 5 sehr intensiv')}`}
function whiteSimpleTaste(){const both=wsComplete(1)&&wsComplete(2);A.innerHTML=brand(`<span class="room">${e(st.theme||R)}</span>`)+`<div class="toprow">${backLink()}</div><div class="tabs"><button class="tab ${g===1?'on':''}" data-ws-glass="1">Wein 1 ${wsComplete(1)?'✓':''}</button><button class="tab ${g===2?'on':''}" data-ws-glass="2">Wein 2 ${wsComplete(2)?'✓':''}</button></div><section class="card tasting">${wsForm()}</section><section class="card compact">${both?'<button id="ws-guess" class="btn primary full">Zuordnung & Fragen</button>':'<b>Je Wein 2–4 Aromen auswählen.</b>'}</section>`;document.querySelectorAll('[data-ws-glass]').forEach(x=>x.onclick=()=>{g=+x.dataset.wsGlass;whiteSimpleTaste()});document.querySelectorAll('[data-ws-k]').forEach(x=>x.onclick=()=>{ans[g][x.dataset.wsK]=+x.dataset.v;wsSave(g);whiteSimpleTaste()});document.querySelectorAll('[data-ws-a]').forEach(x=>x.onclick=()=>{const id=x.dataset.wsA,a=ans[g].aromas;ans[g].aromas=a.includes(id)?a.filter(v=>v!==id):a.length<4?[...a,id]:a;wsSave(g);whiteSimpleTaste()});const b=document.getElementById('ws-guess');if(b)b.onclick=()=>whiteSimpleGuesses()}
async function wsSave(gl){await rpc('save_tasting',{p_code:R,p_token:getSession(R).token,p_glass_no:gl,p_payload:ans[gl]}).catch(x=>toast(x.message))}
async function whiteSimpleGuesses(){let sentences={};try{sentences=await rpc('get_assignment_sentences',{p_code:R,p_token:getSession(R).token})}catch{}const z={},block=(k,l,o)=>`<div class="ttl">${l}</div><div class="grid ${o.length===2?'two':''}">${o.map(([v,t])=>`<button class="choice" data-ws-g="${k}" data-v="${v}">${t}</button>`).join('')}</div>`;A.innerHTML=brand()+`<section class="card"><h2>Zuordnung</h2><p class="muted small">${e(sentences.A||sentences.profile_a||'Profil A')}<br><br>${e(sentences.B||sentences.profile_b||'Profil B')}</p>${block('a','Profil A gehört zu',[[1,'Wein 1'],[2,'Wein 2']])}${block('c','Sicherheit',[[50,'50 %'],[70,'70 %'],[90,'90 %']])}${block('f','Welchen trinkst du lieber?',[[1,'Wein 1'],[2,'Wein 2']])}${block('p','Welchen hältst du für teurer?',[[1,'Wein 1'],[2,'Wein 2']])}<button id="ws-send" class="btn primary full">Antworten speichern</button></section>`;document.querySelectorAll('[data-ws-g]').forEach(x=>x.onclick=()=>{z[x.dataset.wsG]=+x.dataset.v;x.parentElement.querySelectorAll('.choice').forEach(y=>y.classList.remove('on'));x.classList.add('on')});const send=document.getElementById('ws-send');send.onclick=async()=>{if(!z.a||!z.c||!z.f||!z.p)return toast('Bitte alles auswählen');send.disabled=true;try{await rpc('save_guess',{p_code:R,p_token:getSession(R).token,p_profile_a_glass:z.a,p_confidence:z.c,p_favorite_glass:z.f,p_pricier_glass:z.p});waitReveal()}catch(x){send.disabled=false;toast(x.message||'Speichern fehlgeschlagen')}}}

const RED_SIMPLE_AROMAS={kirsche_pflaume:'Kirsche & Pflaume',dunkle_beeren:'Dunkle Beeren',gewuerze_kraeuter:'Gewürze & Kräuter',tabak_leder:'Tabak & Leder',kakao_kaffee:'Kakao & Kaffee',holz_roestung:'Holz & Röstung',lakritz_erdig:'Lakritz & Erde'};
const RED_SIMPLE_TIPS={nose_intensity:'Bewerte nur die Gesamtstärke des Dufts: Wie deutlich meldet sich der Wein, bevor du einzelne Aromen benennst?',aromas:'Nimm nur die Richtungen, die dir tatsächlich auffallen. Es geht um grobe Familien, nicht um das Erraten einer exakten Frucht. Vier Kästchen anzukreuzen ist nicht automatisch besser als zwei präzise.',oak:'Fasse würzige und röstige Eindrücke zusammen. Achte auf Gewürz, Rauch, Toast, Kakao oder Kaffee. Es geht um die Intensität, nicht darum, ob du jede Note benennen kannst.',body:'Achte auf Gewicht und Volumen im Mund. Schlank wirkt leicht und geradlinig; voll wirkt breit und dicht. Alkohol allein ist nicht gleich Körper.',tannin:'Achte auf das trocknende, zusammenziehende Gefühl an Zunge, Zahnfleisch und Wangen. Weich bedeutet wenig Adstringenz, griffig deutlich mehr.',acidity:'Achte auf Frische, Spannung und Speichelfluss nach dem Schluck. Mehr Speichel und Zug sprechen für stärkere Säurewirkung; nicht mit Bitterkeit verwechseln.',retronasal:'Achte darauf, wie stark das Aromabild erst nach dem Schlucken beim Öffnen der Nase aufspringt. Bewerte den Unterschied zwischen Nase zu und Nase offen, nicht die allgemeine Duftstärke.',finish:'Achte darauf, wie lange Geschmack und Aroma nach dem Schlucken klar weiterwirken. Reine Alkoholwärme nicht als langen Abgang werten.'};
function rsTip(k,title='ⓘ Worauf achten?'){const tip=RED_SIMPLE_TIPS[k];return tip?`<details class="sensorytip" data-sensory-tip="${e(k)}"><summary>${e(title)}</summary><p>${e(tip)}</p></details>`:''}
async function redSimpleBoot(S){clearPoll();if(!S||!st.me){const n=getName();if(!n)return joinRoom();try{const d=await rpc('join_tasting',{p_code:R,p_name:n});setSession(R,{token:d.token,name:d.name});return redSimpleBoot(getSession(R))}catch(x){return xRoom(x.message)}}if(st.phase==='revealed')return reveal();const rows=await rpc('get_my_answers',{p_code:R,p_token:S.token});ans={1:blank(),2:blank()};rows.forEach(x=>ans[x.glass_no]={...blank(),...x,aromas:x.aromas||[]});if(st.me.guess_submitted)return waitReveal();redSimpleTaste()}
function rsPick(k,label){return `<div class="ttl">${label}</div><div class="grid">${[1,2,3,4,5].map(v=>`<button class="choice ${ans[g][k]===v?'on':''}" data-rs-k="${k}" data-v="${v}">${v}</button>`).join('')}</div>${rsTip(k)}`}
function rsComplete(gl){const a=ans[gl];return ['nose_intensity','oak','body','tannin','acidity','finish'].every(k=>a[k])&&a.aromas.length>=2&&a.aromas.length<=4}
function rsForm(){const ar=`<div class="ttl">Aromarichtungen – 2 bis 4 auswählen</div><div class="grid two aroma-grid">${Object.entries(RED_SIMPLE_AROMAS).map(([id,label])=>`<button class="choice ${ans[g].aromas.includes(id)?'on':''}" data-rs-a="${id}">${label}</button>`).join('')}</div><p class="small muted">${ans[g].aromas.length}/4 gewählt</p>${rsTip('aromas','ⓘ Wie auswählen?')}`;return `<div class="sectiontitle"><span>🍷</span><div><b>Rotwein bewerten</b></div></div>${rsPick('nose_intensity','Duft- & Fruchtintensität')}${ar}${rsPick('oak','Holz & Röstung')}${rsPick('body','Körper & Fülle')}${rsPick('tannin','Tanningriff')}${rsPick('acidity','Frische & Säure')}${rsPick('finish','Länge & Intensität des Abgangs')}`}
function redSimpleTaste(){const both=rsComplete(1)&&rsComplete(2);A.innerHTML=brand(`<span class="room">${e(st.theme||R)}</span>`)+`<div class="toprow">${backLink()}</div><div class="tabs"><button class="tab ${g===1?'on':''}" data-rs-glass="1">Wein 1 ${rsComplete(1)?'✓':''}</button><button class="tab ${g===2?'on':''}" data-rs-glass="2">Wein 2 ${rsComplete(2)?'✓':''}</button></div><section class="card tasting">${rsForm()}</section><section class="card compact">${both?'<button id="rs-guess" class="btn primary full">Zuordnung & Fragen</button>':'<b>Je Wein 2–4 Aromen auswählen.</b>'}</section>`;document.querySelectorAll('[data-rs-glass]').forEach(x=>x.onclick=()=>{g=+x.dataset.rsGlass;redSimpleTaste()});document.querySelectorAll('[data-rs-k]').forEach(x=>x.onclick=()=>{ans[g][x.dataset.rsK]=+x.dataset.v;rsSave(g);redSimpleTaste()});document.querySelectorAll('[data-rs-a]').forEach(x=>x.onclick=()=>{const id=x.dataset.rsA,a=ans[g].aromas;ans[g].aromas=a.includes(id)?a.filter(v=>v!==id):a.length<4?[...a,id]:a;rsSave(g);redSimpleTaste()});const b=document.getElementById('rs-guess');if(b)b.onclick=()=>whiteSimpleGuesses()}
async function rsSave(gl){await rpc('save_tasting',{p_code:R,p_token:getSession(R).token,p_glass_no:gl,p_payload:ans[gl]}).catch(x=>toast(x.message))}
async function roomBoot(){clearPoll();const S=getSession(R);try{st=await rpc('get_public_state',{p_code:R,p_token:S?.token||null})}catch(x){return xRoom(x.message||'Tasting-Raum nicht gefunden')}if(st.tasting_type==='white_solo')return soloBoot(S);if(st.tasting_type==='white_simple')return whiteSimpleBoot(S);if(st.tasting_type==='red_simple')return redSimpleBoot(S);return xRoom('Dieser ältere Raumtyp ist momentan nicht verfügbar.')}

function hostRoomTitle(r){const meta=r.tasting_type==='white_solo'&&typeof soloWineMeta==='function'?soloWineMeta(r.code):null;return meta?.name||r.theme}
function hostCard(r){const pair=['red_simple','white_simple'].includes(r.tasting_type),solo=r.tasting_type==='white_solo',ready=r.participants>0&&r.tasting_done===r.participants&&r.guesses_done===r.participants,stats=`<div class="stats"><div class="stat"><b>${r.participants}</b>Teilnehmer</div><div class="stat"><b>${r.tasting_done}</b>fertig</div><div class="stat"><b>${r.guesses_done}</b>Antworten</div></div>`,title=hostRoomTitle(r);if(r.phase==='revealed')return `<section class="card pair"><h3>${e(title)}</h3>${stats}<div class="hint ok">Aufgelöst${pair&&r.actual_a_glass?` · A war Wein ${r.actual_a_glass}`:''}</div></section>`;if(pair)return `<section class="card pair"><h3>${e(title)}</h3>${stats}<div class="hint"><b>Profil A:</b> ${e(r.profile_a||'Wein A')}<br><b>Profil B:</b> ${e(r.profile_b||'Wein B')}</div><p class="muted small">Erst nach dem Ausschenken festlegen, welcher Wein tatsächlich in Glas 1 und Glas 2 war.</p><button class="btn primary full" data-pair-map="1" data-room="${e(r.code)}" ${ready?'':'disabled'}>A = Wein 1 · B = Wein 2</button><button class="btn secondary full" data-pair-map="2" data-room="${e(r.code)}" ${ready?'':'disabled'}>A = Wein 2 · B = Wein 1</button>${ready?'':'<p class="muted small">Freigabe erst möglich, wenn alle fertig sind.</p>'}</section>`;if(solo)return `<section class="card pair"><h3>${e(title)}</h3>${stats}<button class="btn primary full" data-phase="revealed" data-room="${e(r.code)}" ${ready?'':'disabled'}>Auflösung freigeben</button></section>`;return `<section class="card pair"><h3>${e(title)}</h3>${stats}${r.phase==='tasting'?`<button class="btn primary full" data-phase="profiles" data-room="${e(r.code)}">Profile freigeben</button>`:'<button class="btn primary full" data-phase="revealed" data-room="'+e(r.code)+'">Auflösung freigeben</button>'}</section>`}
document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-pair-map]');if(!b||b.disabled)return;ev.preventDefault();const aGlass=+b.dataset.pairMap,room=b.dataset.room,label=aGlass===1?'A = Wein 1 und B = Wein 2':'A = Wein 2 und B = Wein 1';if(!confirm(`${label}\n\nZuordnung speichern und jetzt auflösen?`))return;b.disabled=true;try{await rpc('host_reveal_pair',{p_event_code:E,p_host_token:H,p_room_code:room,p_profile_a_glass:aGlass});hostPortal()}catch(x){b.disabled=false;toast(x.message)}});
async function portal(){if(q.get('hostmode')==='1'&&!H)return hostGate();let d;try{d=await rpc('get_event_state',{p_event_code:E})}catch(x){A.innerHTML=brand()+`<section class="card"><h2>Portal nicht gefunden</h2><p class="muted">${e(x.message)}</p></section>`;return}if(KIOSK)return kioskPortal(d);const name=getName();if(!name){A.innerHTML=brand(`<span class="room">Portal</span>`)+`<section class="card hero"><h2>${e(d.title)}</h2><p class="muted">Gib deinen Namen ein, damit du deine Antworten später auf demselben Gerät wieder aufnehmen kannst.</p><div class="field"><label>Dein Name</label><input id="portal-name" maxlength="40" autocomplete="name" placeholder="Name eingeben"></div><button id="portal-start" class="btn primary full">Tastings anzeigen</button></section>`;const input=document.getElementById('portal-name');const submit=()=>{const n=input.value.trim();if(!n)return toast('Bitte gib deinen Namen ein');setActiveName(n);portal()};document.getElementById('portal-start').onclick=submit;input.onkeydown=x=>{if(x.key==='Enter')submit()};input.focus();return}const history=await loadEventLeaderboard(d);A.innerHTML=brand(`<span class="room">${e(name)}</span>`)+`<section class="card hero"><h2>${e(d.title)}</h2><button id="change-name" class="linkbtn">Name wechseln</button></section><div class="pairlist">${d.rooms.map(pairCard).join('')}</div>${eventLeaderboard(history,'Abend-Leaderboard')}`;document.getElementById('change-name').onclick=()=>{clearActiveName();portal()};document.querySelectorAll('[data-room]').forEach(x=>x.onclick=()=>{location.href=`?event=${encodeURIComponent(E)}&room=${encodeURIComponent(x.dataset.room)}`})}

const REVEAL_LABELS={nose_intensity:'Duft- & Fruchtintensität',oak:'Holz & Röstung',tannin:'Tanningriff',acidity:'Frische & Säure',freshness:'Frische',body:'Körper & Fülle',finish:'Länge des Abgangs',finish_intensity:'Intensität des Abgangs'};
function revealLabel(k,type){if(k==='oak'&&type==='white_simple')return'Schmelz & Cremigkeit';if(k==='tannin'&&type==='white_simple')return'Süße-Eindruck';if(k==='acidity'&&type==='white_simple')return'Säure';return REVEAL_LABELS[k]||k}
function revealAromaLabel(id,type){return(type==='white_simple'?SOLO_AROMAS:RED_SIMPLE_AROMAS)[id]||String(id).replaceAll('_',' ')}
function revealScore(v){const n=Number(v||0);return Number.isInteger(n)?String(n):n.toFixed(1)}
function revealStatus(m){const d=Math.abs(Number(m.actual)-Number(m.expected));return d===0?['exact','Genau getroffen']:d===1?['near','Knapp daneben']:['miss','Deutlich abweichend']}
function revealScale(m){return`<div class="resultscale">${[1,2,3,4,5].map(v=>`<span class="${v===Number(m.actual)?'mine ':''}${v===Number(m.expected)?'target ':''}${v===Number(m.actual)&&v===Number(m.expected)?'both':''}">${v}</span>`).join('')}</div><div class="scalelegend"><span>Dein Wert <b>${m.actual}</b></span><span>Ziel <b>${m.expected}</b></span></div>`}
function revealMetric(m,type){const [tone,text]=revealStatus(m);return`<div class="resultmetric ${tone}"><div class="resultmetrichead"><b>${e(revealLabel(m.key,type))}</b><span>${text} · ${revealScore(m.score)}/${revealScore(m.max)} P.</span></div>${revealScale(m)}</div>`}
function revealTags(ids,type,tone=''){return(ids||[]).map(id=>`<span class="aromatag ${tone}">${e(revealAromaLabel(id,type))}</span>`).join('')||'<span class="muted small">–</span>'}
function revealDossier(d,type){const w=d.wine||{},x=w.details||{},p=w.profile||{},notes=p.key||[];return`<article class="dossier"><div class="dossierhead"><div><div class="ey">Wein ${d.glass}</div><h3>${e(w.name)} ${e(w.vintage||'')}</h3></div><div class="glassbadge">${d.glass}</div></div><p class="lead">${e(p.summary||x.sources_summary||'')}</p><div class="factgrid">${x.producer?`<div><small>Winzer</small><b>${e(x.producer)}</b></div>`:''}${x.region?`<div><small>Herkunft</small><b>${e(x.region)}</b></div>`:''}${x.grapes?`<div><small>Rebsorten</small><b>${e(x.grapes)}</b></div>`:''}${x.price_band_eur?`<div><small>Preis</small><b>${e(x.price_band_eur)}</b></div>`:''}${x.serve?`<div><small>Servieren</small><b>${e(x.serve)}</b></div>`:''}</div>${notes.length?`<div class="dossiersection"><h4>Typische Aromen</h4><div class="tags">${notes.map(n=>`<span class="tag strong">${e(n)}</span>`).join('')}</div></div>`:''}${p.nose||p.palate?`<div class="dossiersection twocol"><div><h4>Nase</h4><p>${e(p.nose||'')}</p></div><div><h4>Gaumen & Abgang</h4><p>${e(p.palate||'')} ${e(p.finish||'')}</p></div></div>`:''}${x.winemaking?`<div class="dossiersection"><h4>Herstellung & Keller</h4><p>${e(x.winemaking)}</p></div>`:''}${x.special?`<div class="dossiersection special"><h4>Was diesen Wein besonders macht</h4><p>${e(x.special)}</p></div>`:''}${x.sources_summary?`<details><summary>Ausführliches Weinporträt</summary><p class="small">${e(x.sources_summary)}</p></details>`:''}${x.critics?`<p class="critics"><b>Kritiker:</b> ${e(x.critics)}</p>`:''}</article>`}
function revealPersonalGlass(d,type){const a=d.aromas||{};return`<article class="personalwine"><div class="personalhead"><div><div class="ey">Dein Profil · Wein ${d.glass}</div><h3>${e(d.wine?.name||'')}</h3></div><div class="roundscore">${revealScore(d.score)}<small>/19</small></div></div>${(d.metrics||[]).map(m=>revealMetric(m,type)).join('')}<div class="aromaresult"><div class="resultmetrichead"><b>Aromarichtungen</b><span>${revealScore(a.score)}/${revealScore(a.max)} P.</span></div><p class="tiny muted">Grün = getroffen · Rot = im Zielprofil, aber nicht gewählt · Grau = zusätzlich gewählt</p><div class="aromagroups"><div><small>Treffer</small><div class="aromachips">${revealTags(a.matched,type,'hit')}</div></div><div><small>Nicht erkannt</small><div class="aromachips">${revealTags(a.missed,type,'missed')}</div></div>${(a.extra||[]).length?`<div><small>Zusätzlich gewählt</small><div class="aromachips">${revealTags(a.extra,type,'extra')}</div></div>`:''}</div></div>${d.note?`<blockquote>„${e(d.note)}“</blockquote>`:''}</article>`}
function revealBreakdown(me){const b=me?.breakdown||{},rows=[['Duft',b.nose,b.nose_max],['Aromen & Ausbau',b.aromas,b.aromas_max],['Struktur',b.structure,b.structure_max],['Abgang',b.finish,b.finish_max],['Zuordnung',b.assignment,b.assignment_max]];return`<div class="scorestory">${rows.map(([l,v,m])=>`<div><div class="barlabel"><span>${l}</span><b>${revealScore(v)}/${revealScore(m)}</b></div><div class="bar"><i style="width:${m?Math.min(100,100*Number(v||0)/Number(m)):0}%"></i></div></div>`).join('')}</div>`}
function revealConsensus(r,d,type){const stats=r.glass_stats||[];return(d.glasses||[]).map(gl=>{const top=(r.aroma_consensus||[]).filter(x=>Number(x.glass)===Number(gl.glass)).slice(0,6),av=stats.find(x=>Number(x.glass)===Number(gl.glass))?.averages||{};return`<article class="groupwine"><div class="ey">Gruppe · Wein ${gl.glass}</div><h3>${e(gl.wine?.name||'')}</h3><h4>Dominant wahrgenommene Aromen</h4>${top.map(x=>`<div class="consensusrow"><span>${e(revealAromaLabel(x.aroma,type))}</span><div class="bar"><i style="width:${Number(x.pct)||0}%"></i></div><b>${x.pct}%</b></div>`).join('')||'<p class="muted small">Keine Aromadaten</p>'}<h4>Gruppenmittel vs. Ziel</h4>${(gl.metrics||[]).map(m=>`<div class="avgcompare"><span>${e(revealLabel(m.key,type))}</span><b>${av[m.key]??'–'}</b><small>Ziel ${m.expected}</small></div>`).join('')}</article>`}).join('')}
function revealVoteBar(title,a,b){const total=Number(a||0)+Number(b||0),one=total?Math.round(100*Number(a||0)/total):50;return`<div class="voteblock"><div class="barlabel"><b>${e(title)}</b><span>${a||0} : ${b||0}</span></div><div class="splitbar"><i style="width:${one}%">Wein 1</i><em style="width:${100-one}%">Wein 2</em></div></div>`}
function richRanks(lb){return(lb||[]).map((x,i)=>`<div class="rank"><div class="n">${i+1}</div><div><b>${e(x.name)}</b><div class="minibar"><i style="width:${100*Number(x.score||0)/Number(x.max_score||46)}%"></i></div></div><div class="score">${revealScore(x.score)}/${x.max_score}</div></div>`).join('')}
async function reveal(){clearPoll();const S=getSession(R),args={p_code:R,p_token:S.token};let r,d;try{[r,d]=await Promise.all([rpcCompat('get_reveal_v2','get_reveal',args),rpc('get_reveal_detail',args)])}catch(x){return xRoom(x.message||'Auflösung konnte nicht geladen werden')}const me=r.personal||r.leaderboard.find(x=>String(x.name).toLowerCase()===String(S.name).toLowerCase()),type=r.tasting_type||d.tasting_type,v=r.votes||{};A.innerHTML=brand(`<span class="room">Auflösung</span>`)+`<div class="toprow">${backLink()}</div><section class="card hero resulthero"><div class="ey">${e(r.theme||R)} · Profil A war Wein ${r.profile_a_glass}</div><div class="heroresult"><div><h2>${e(me?.name||S.name)}</h2><p>${me?.profile_correct?'✓ Satz-Zuordnung richtig':'Satz-Zuordnung nicht getroffen'} · Sicherheit ${me?.confidence||'–'}%</p></div><div class="totalscore">${revealScore(me?.score)}<small>/ ${me?.max_score||46}</small></div></div>${revealBreakdown(me)}</section><section class="resultsection"><div class="sectionheading"><span>🍷</span><div><h2>Die Weine</h2><p>Herkunft, Winzer, Herstellung und sensorisches Profil</p></div></div><div class="dossiergrid">${(d.glasses||[]).map(x=>revealDossier(x,type)).join('')}</div></section><section class="resultsection"><div class="sectionheading"><span>🎯</span><div><h2>Deine Detailauswertung</h2><p>Dein Wert, Zielprofil und Punkte je Kategorie</p></div></div><div class="personalgrid">${(d.glasses||[]).map(x=>revealPersonalGlass(x,type)).join('')}</div></section><section class="card"><div class="sectionheading compactheading"><span>👥</span><div><h2>So hat die Gruppe verkostet</h2><p>Dominante Aromen und Durchschnittswerte</p></div></div><div class="groupgrid">${revealConsensus(r,d,type)}</div>${revealVoteBar('Lieblingswein',v.favorite1,v.favorite2)}${revealVoteBar('Für teurer gehalten',v.pricier1,v.pricier2)}</section><section class="card"><div class="sectionheading compactheading"><span>🏆</span><div><h2>Leaderboard</h2><p>Gesamtpunkte aus Profilnähe und Zuordnung</p></div></div>${richRanks(r.leaderboard)}</section>`}
// OLIRED: a spoiler-safe pair card and one extra, guided retronasal category.
function rsHasRetronasal(){return st?.room_code==='OLIRED'}
function rsComplete(gl){const a=ans[gl],keys=['nose_intensity','oak','body','tannin','acidity','finish'];if(rsHasRetronasal())keys.push('retronasal');return keys.every(k=>a[k])&&a.aromas.length>=2&&a.aromas.length<=4}
function retronasalExperiment(){return `<div class="senseexperiment"><div class="sectiontitle"><span>🌬️</span><div><b>Postnasale Geschmacksexplosion</b><p class="muted small">Der direkte Vergleich zeigt, wie stark Aromen erst über den Rachen zur Nase aufsteigen.</p></div></div><ol><li>Einen kleinen Schluck nehmen und die Nase zuhalten.</li><li>Schlucken, dann die Nase öffnen und ruhig ausatmen.</li><li>Wie stark springt das Aromabild jetzt auf?</li></ol><picture class="postnasalguide"><source srcset="assets/postnasal-anleitung-static.svg" media="(prefers-reduced-motion: reduce)"><img src="assets/postnasal-anleitung-animated.svg" alt="Bildanleitung in fünf Schritten: Nase mit zwei Fingern zuhalten, kleinen Schluck nehmen, schlucken und Glas absetzen, Nase öffnen und ruhig ausatmen, erneut am Glas riechen und vergleichen." loading="lazy"></picture>${rsPick('retronasal','Unterschied zwischen Nase zu und Nase offen')}<div class="scalecaptions"><span>1 · kaum</span><span>5 · explosiv</span></div></div>`}
function rsForm(){const ar=`<div class="ttl">Aromarichtungen – 2 bis 4 auswählen</div><div class="grid two aroma-grid">${Object.entries(RED_SIMPLE_AROMAS).map(([id,label])=>`<button class="choice ${ans[g].aromas.includes(id)?'on':''}" data-rs-a="${id}">${label}</button>`).join('')}</div><p class="small muted">${ans[g].aromas.length}/4 gewählt</p>${rsTip('aromas','ⓘ Wie auswählen?')}`;return `<div class="sectiontitle"><span>🍷</span><div><b>Rotwein bewerten</b><p class="muted small">Alle Angaben bleiben bis zur Host-Auflösung blind.</p></div></div>${rsPick('nose_intensity','Duft- & Fruchtintensität')}${ar}${rsPick('oak','Holz & Röstung')}${rsPick('body','Körper & Fülle')}${rsPick('tannin','Tanningriff')}${rsPick('acidity','Frische & Säure')}${rsHasRetronasal()?retronasalExperiment():''}${rsPick('finish','Länge & Intensität des Abgangs')}`}

function blindDuoIcon(){return `<div class="blindduo" aria-hidden="true"><span class="bottle one"></span><span class="bottle two"></span><i>?</i></div>`}
function pairCard(r){const s=getSession(r.code),phase=r.phase==='tasting'?'Freie Verkostung':r.phase==='profiles'?'Profile offen':'Aufgelöst',white=isWhiteType(r.tasting_type),olli=r.code==='OLIRED';return `<section class="card pair ${white?'whitepair':'redpair'} ${olli?'olliredcard':''}"><div class="pairtop"><div class="pairidentity">${olli?blindDuoIcon():`<div class="standardicon">${white?'🥂':'🍷'}</div>`}<div><div class="ey">${olli?'Blindes Rotwein-Duo':white?'Weißwein':'Rotwein'}</div><h3>${e(r.theme)}</h3></div></div><span class="pill">${phase}</span></div><p class="muted small">${e(r.intro||'')}</p><a class="btn ${s?'secondary':'primary'} full center" href="?event=${encodeURIComponent(E)}&room=${encodeURIComponent(r.code)}${KIOSK?'&kiosk=1':''}">${s?'Weiter':'Starten'}</a></section>`}

REVEAL_LABELS.retronasal='Postnasale Geschmacksexplosion';
function revealBreakdown(me){const b=me?.breakdown||{},retro=Number(b.finish_max)===8,rows=[['Duft',b.nose,b.nose_max],['Aromen & Ausbau',b.aromas,b.aromas_max],['Struktur',b.structure,b.structure_max],[retro?'Nachhall & Abgang':'Abgang',b.finish,b.finish_max],['Zuordnung',b.assignment,b.assignment_max]];return `<div class="scorestory">${rows.map(([l,v,m])=>`<div><div class="barlabel"><span>${l}</span><b>${revealScore(v)}/${revealScore(m)}</b></div><div class="bar"><i style="width:${m?Math.min(100,100*Number(v||0)/Number(m)):0}%"></i></div></div>`).join('')}</div>`}
function wineInitials(name=''){return String(name).replace(/[^A-Za-zÀ-ÿ0-9 ]/g,' ').split(/\s+/).filter(Boolean).slice(0,3).map(x=>x[0]).join('').toUpperCase()}
function revealDossier(d,type){const w=d.wine||{},x=w.details||{},p=w.profile||{},notes=p.key||[],rhx=/vacqueyras|rhône/i.test(`${x.region||''} ${w.name||''}`);return `<article class="dossier"><div class="winevisual ${rhx?'warm':'cool'}" aria-hidden="true"><span class="neck"></span><span class="bottlebody"><i>${e(wineInitials(w.name))}</i></span><em>Wein ${d.glass}</em></div><div class="dossierhead"><div><div class="ey">Wein ${d.glass}</div><h3>${e(w.name)} ${e(w.vintage||'')}</h3></div><div class="glassbadge">${d.glass}</div></div><p class="lead">${e(p.summary||x.sources_summary||'')}</p><div class="factgrid">${x.producer?`<div><small>Winzer</small><b>${e(x.producer)}</b></div>`:''}${x.region?`<div><small>Herkunft</small><b>${e(x.region)}</b></div>`:''}${x.grapes?`<div><small>Rebsorten</small><b>${e(x.grapes)}</b></div>`:''}${x.price_band_eur?`<div><small>Preis</small><b>${e(x.price_band_eur)}</b></div>`:''}${x.serve?`<div><small>Servieren</small><b>${e(x.serve)}</b></div>`:''}</div>${notes.length?`<div class="dossiersection"><h4>Typische Aromen</h4><div class="tags">${notes.map(n=>`<span class="tag strong">${e(n)}</span>`).join('')}</div></div>`:''}${p.nose||p.palate?`<div class="dossiersection twocol"><div><h4>Nase</h4><p>${e(p.nose||'')}</p></div><div><h4>Gaumen & Abgang</h4><p>${e(p.palate||'')} ${e(p.finish||'')}</p></div></div>`:''}${x.winemaking?`<div class="dossiersection"><h4>Herstellung & Keller</h4><p>${e(x.winemaking)}</p></div>`:''}${x.special?`<div class="dossiersection special"><h4>Was diesen Wein besonders macht</h4><p>${e(x.special)}</p></div>`:''}${x.sources_summary?`<details><summary>Ausführliches Weinporträt</summary><p class="small">${e(x.sources_summary)}</p></details>`:''}${x.critics?`<p class="critics"><b>Einordnung:</b> ${e(x.critics)}</p>`:''}</article>`}

// Event hub: leaderboard, revealed-wine archive and cumulative score chart.
function isParticipantHost(){return String(getName()||'').trim().toLowerCase()==='axel'}
function eventTab(){const tab=q.get('tab');return tab==='stand'?'stand':tab==='host'&&isParticipantHost()?'host':'tastings'}
function eventUrl(tab,kiosk=KIOSK){return `?event=${encodeURIComponent(E)}${tab==='stand'?'&tab=stand':tab==='host'?'&tab=host':''}${kiosk?'&kiosk=1':''}`}
function eventTabs(active){const host=isParticipantHost();return `<nav class="eventtabs ${host?'hosttabs':''}" aria-label="Event-Navigation"><a class="${active==='tastings'?'on':''}" href="${eventUrl('tastings')}" data-nav="${eventUrl('tastings')}"><span>🍷</span>Tastings</a><a class="${active==='stand'?'on':''}" href="${eventUrl('stand')}" data-nav="${eventUrl('stand')}"><span>🏆</span>Abendstand</a>${host?`<a class="${active==='host'?'on':''}" href="${eventUrl('host')}" data-nav="${eventUrl('host')}"><span>🔓</span>Host</a>`:''}</nav>`}
async function loadEventOverview(){return rpc('get_event_overview',{p_event_code:E})}
function eventRanks(players){return (players||[]).map((x,i)=>`<div class="rank eventrank"><div class="n">${i+1}</div><div><b>${e(x.name)}</b><small>${x.rounds_played||0} Runde${Number(x.rounds_played)===1?'':'n'}</small><div class="minibar"><i style="width:${x.max_total?Math.min(100,100*Number(x.total||0)/Number(x.max_total)):0}%"></i></div></div><div class="score">${revealScore(x.total)}/${revealScore(x.max_total)}</div></div>`).join('')||'<p class="muted">Noch keine aufgelösten Ergebnisse.</p>'}
function expertAwards(awards){if(!(awards||[]).length)return'';return `<section class="card expertsection"><div class="sectionheading compactheading"><span>🎖️</span><div><h2>Experten des Abends</h2><p>Trefferquote aus allen aufgelösten Verkostungen</p></div></div><div class="expertgrid">${awards.map(x=>`<article class="expertaward"><span class="experticon" aria-hidden="true">${e(x.icon||'🏅')}</span><div><small>${e(x.label)}</small><b>${e(x.name)}</b><em>${revealScore(x.accuracy)} % · ${Number(x.samples)||0} Wertungen</em></div></article>`).join('')}</div><p class="expertnote">Aroma zählt erkannte Aromafamilien, Tannin den Tanningriff bei Rotwein und Nasal die Genauigkeit von Nase und postnasalem Eindruck. Laufende Runden zählen erst nach der Auflösung.</p></section>`}
function eventChart(t){const rounds=t?.rounds||[],players=t?.players||[];if(!rounds.length||!players.length)return '<div class="emptychart"><span>📈</span><p>Der Punkteverlauf erscheint nach der ersten aufgelösten Runde.</p></div>';const W=Math.max(620,130*rounds.length+100),H=300,L=52,Rg=22,Tp=20,B=64,max=Math.max(Number(t.event_max)||1,...players.flatMap(p=>(p.points||[]).map(x=>Number(x.cumulative)||0))),x=i=>rounds.length===1?W/2:L+i*(W-L-Rg)/(rounds.length-1),y=v=>Tp+(H-Tp-B)*(1-Number(v||0)/max),ticks=[0,.25,.5,.75,1];const grids=ticks.map(f=>`<line class="gridline" x1="${L}" y1="${y(max*f)}" x2="${W-Rg}" y2="${y(max*f)}"></line><text class="axistext" x="${L-8}" y="${y(max*f)+4}" text-anchor="end">${Math.round(max*f)}</text>`).join('');const labels=rounds.map((r,i)=>`<text class="xtext" x="${x(i)}" y="${H-25}" text-anchor="middle">R${r.round_no}</text><text class="xtext mutedx" x="${x(i)}" y="${H-10}" text-anchor="middle">${e(String(r.theme).slice(0,16))}</text>`).join('');const lines=players.map((p,pi)=>{const color=lineColors[pi%lineColors.length],pts=(p.points||[]).map((v,i)=>[x(i),y(v.cumulative),v]);const path=pts.map((v,i)=>`${i?'L':'M'} ${v[0].toFixed(1)} ${v[1].toFixed(1)}`).join(' ');return `<path d="${path}" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"></path>${pts.map(v=>`<circle cx="${v[0]}" cy="${v[1]}" r="4" fill="${color}"><title>${e(p.name)}: ${revealScore(v[2].cumulative)} Punkte</title></circle>`).join('')}`}).join('');return `<div class="legend">${players.map((p,i)=>`<span><i style="background:${lineColors[i%lineColors.length]}"></i>${e(p.name)}</span>`).join('')}</div><div class="chartwrap"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Kumulativer Punkteverlauf">${grids}${lines}${labels}</svg></div>`}
function compactWine(w,i){if(!w)return'';const p=w.profile||{},x=w.details||{};return `<article class="archivewine"><div class="archivebottle">${i+1}</div><div><div class="ey">Wein ${i+1}</div><h4>${e(w.name)} ${e(w.vintage||'')}</h4><p>${e(p.summary||'')}</p><div class="archivefacts">${x.producer?`<span><b>Winzer</b>${e(x.producer)}</span>`:''}${x.region?`<span><b>Region</b>${e(x.region)}</span>`:''}${x.grapes?`<span><b>Rebsorten</b>${e(x.grapes)}</span>`:''}${x.serve?`<span><b>Servieren</b>${e(x.serve)}</span>`:''}</div>${Array.isArray(p.key)?`<div class="tags">${p.key.slice(0,7).map(a=>`<span class="tag strong">${e(a)}</span>`).join('')}</div>`:''}</div></article>`}
function wineArchive(rooms){if(!(rooms||[]).length)return '<section class="card"><h3>Noch keine Weine aufgedeckt</h3><p class="muted">Hier erscheinen ausschließlich bereits vom Host aufgelöste Flaschen.</p></section>';return rooms.map(r=>`<section class="card archive"><div class="archivehead"><div><div class="ey">Aufgelöste Runde</div><h3>${e(r.theme)}</h3></div><span class="pill done">✓ Aufgedeckt</span></div><div class="archivegrid">${(r.wines||[]).map(compactWine).join('')}</div><details><summary>Runden-Ergebnis</summary>${richRanks(r.leaderboard||[])}</details></section>`).join('')}
function renderEventHub(o,person,kiosk=false){const t=o.timeline||{};A.innerHTML=brand(`<span class="room">${e(person)}</span>`)+eventTabs('stand')+`<section class="card hero eventhero"><div class="ey">Aktueller Stand</div><h2>${e(o.title)}</h2><p class="muted">Nur bereits aufgelöste Runden und Weine werden hier angezeigt.</p></section><section class="card"><div class="sectionheading compactheading"><span>🏆</span><div><h2>Abend-Leaderboard</h2><p>${t.round_count||0} aufgelöste Runde${Number(t.round_count)===1?'':'n'}</p></div></div>${eventRanks(t.players)}</section>${expertAwards(o.expert_awards)}<section class="card timelinecard"><div class="sectionheading compactheading"><span>📈</span><div><h2>Punkteverlauf</h2><p>Kumulierte Punkte nach jeder Auflösung</p></div></div>${eventChart(t)}</section><div class="sectionheading archiveheading"><span>📚</span><div><h2>Getestete Weine</h2><p>Das Archiv wächst mit jeder Host-Auflösung</p></div></div>${wineArchive(o.rooms)}`}
function participantHostTokens(rooms){return [...new Set((rooms||[]).map(r=>getSession(r.code)?.token).filter(Boolean))]}
function participantHostCard(r){const pair=['red_simple','white_simple'].includes(r.tasting_type),solo=r.tasting_type==='white_solo',ready=r.participants>0&&r.tasting_done===r.participants&&r.guesses_done===r.participants,stats=`<div class="stats"><div class="stat"><b>${r.participants}</b>Teilnehmer</div><div class="stat"><b>${r.tasting_done}</b>fertig</div><div class="stat"><b>${r.guesses_done}</b>Antworten</div></div>`,title=hostRoomTitle(r);if(r.phase==='revealed')return `<section class="card pair"><h3>${e(title)}</h3>${stats}<div class="hint ok">Aufgelöst${pair&&r.actual_a_glass?` · A war Wein ${r.actual_a_glass}`:''}</div></section>`;if(pair)return `<section class="card pair"><h3>${e(title)}</h3>${stats}<div class="hint"><b>Profil A:</b> ${e(r.profile_a||'Wein A')}<br><b>Profil B:</b> ${e(r.profile_b||'Wein B')}</div><button class="btn primary full" data-player-host-pair="1" data-room="${e(r.code)}" ${ready?'':'disabled'}>A = Wein 1 · B = Wein 2</button><button class="btn secondary full" data-player-host-pair="2" data-room="${e(r.code)}" ${ready?'':'disabled'}>A = Wein 2 · B = Wein 1</button>${ready?'':'<p class="muted small">Freigabe erst möglich, wenn alle fertig sind.</p>'}</section>`;if(solo)return `<section class="card pair"><h3>${e(title)}</h3>${stats}<button class="btn primary full" data-player-host-phase="revealed" data-room="${e(r.code)}" ${ready?'':'disabled'}>Auflösung freigeben</button>${ready?'':'<p class="muted small">Freigabe erst möglich, wenn alle Bewertung und Tipps abgeschlossen haben.</p>'}</section>`;return `<section class="card pair"><h3>${e(title)}</h3>${stats}${r.phase==='tasting'?`<button class="btn primary full" data-player-host-phase="profiles" data-room="${e(r.code)}">Profile freigeben</button>`:`<button class="btn primary full" data-player-host-phase="revealed" data-room="${e(r.code)}">Auflösung freigeben</button>`}</section>`}
async function participantHostPortal(d){clearPoll();const tokens=participantHostTokens(d.rooms);if(!tokens.length){A.innerHTML=brand(`<span class="room">Axel · Host</span>`)+eventTabs('host')+`<section class="card hero"><div class="ey">🔓 Mitspieler-Host</div><h2>Noch keine Sitzung auf diesem Gerät</h2><p class="muted">Öffne zuerst eines deiner bereits gestarteten Tastings. Danach ist dieser Host-Tab automatisch freigeschaltet.</p></section>`;return}let h;try{h=await rpc('participant_host_get_event_state',{p_event_code:E,p_participant_tokens:tokens})}catch(x){A.innerHTML=brand(`<span class="room">Axel · Host</span>`)+eventTabs('host')+`<section class="card hero"><div class="ey">🔓 Mitspieler-Host</div><h2>Host-Berechtigung nicht gefunden</h2><p class="muted">${e(x.message||'Bitte eine bestehende Axel-Sitzung auf diesem Gerät öffnen.')}</p></section>`;return}A.innerHTML=brand(`<span class="room">Axel · Host</span>`)+eventTabs('host')+`<section class="card hero"><div class="ey">🔓 Mitspieler-Host</div><h2>Runden freigeben</h2><p class="muted small">Axels Teilnehmer-Sitzung ist als Host autorisiert. Freigaben gelten sofort für alle.</p></section><div class="pairlist">${h.rooms.map(participantHostCard).join('')}</div>`;document.querySelectorAll('[data-player-host-phase]').forEach(x=>x.onclick=async()=>{if(x.disabled)return;const phase=x.dataset.playerHostPhase,room=x.dataset.room;if(!confirm(phase==='profiles'?'Profile freigeben?':'Jetzt auflösen?'))return;clearPoll();x.disabled=true;try{await rpc('participant_host_set_room_phase',{p_event_code:E,p_participant_tokens:tokens,p_room_code:room,p_phase:phase});participantHostPortal(d)}catch(err){x.disabled=false;toast(err?.message||'Freigabe fehlgeschlagen');poll=setTimeout(()=>participantHostPortal(d),5000)}});document.querySelectorAll('[data-player-host-pair]').forEach(x=>x.onclick=async()=>{if(x.disabled)return;const aGlass=+x.dataset.playerHostPair,room=x.dataset.room,label=aGlass===1?'A = Wein 1 und B = Wein 2':'A = Wein 2 und B = Wein 1';if(!confirm(`${label}\n\nZuordnung speichern und jetzt auflösen?`))return;clearPoll();x.disabled=true;try{await rpc('participant_host_reveal_pair',{p_event_code:E,p_participant_tokens:tokens,p_room_code:room,p_profile_a_glass:aGlass});participantHostPortal(d)}catch(err){x.disabled=false;toast(err?.message||'Auflösung fehlgeschlagen');poll=setTimeout(()=>participantHostPortal(d),5000)}});poll=setTimeout(()=>participantHostPortal(d),5000)}
async function portal(){if(q.get('hostmode')==='1'&&!H)return hostGate();let d;try{d=await rpc('get_event_state',{p_event_code:E})}catch(x){A.innerHTML=brand()+`<section class="card"><h2>Portal nicht gefunden</h2><p class="muted">${e(x.message)}</p></section>`;return}if(KIOSK)return kioskPortal(d);const name=getName();if(!name){A.innerHTML=brand(`<span class="room">Portal</span>`)+`<section class="card hero"><h2>${e(d.title)}</h2><p class="muted">Gib deinen Namen ein, damit Antworten und Abendstand auf diesem Gerät wieder aufgenommen werden können.</p><div class="field"><label>Dein Name</label><input id="portal-name" maxlength="40" autocomplete="name" placeholder="Name eingeben"></div><button id="portal-start" class="btn primary full">Zum Weinabend</button></section>`;const input=document.getElementById('portal-name'),submit=()=>{const n=input.value.trim();if(!n)return toast('Bitte gib deinen Namen ein');setActiveName(n);portal()};document.getElementById('portal-start').onclick=submit;input.onkeydown=x=>{if(x.key==='Enter')submit()};input.focus();return}if(eventTab()==='stand'){try{return renderEventHub(await loadEventOverview(),name)}catch(x){return xRoom(x.message||'Abendstand konnte nicht geladen werden')}}if(eventTab()==='host')return participantHostPortal(d);A.innerHTML=brand(`<span class="room">${e(name)}</span>`)+eventTabs('tastings')+`<section class="card hero"><h2>${e(d.title)}</h2><button id="change-name" class="linkbtn">Name wechseln</button></section><div class="pairlist">${d.rooms.map(pairCard).join('')}</div>${hostEntry()}`;document.getElementById('change-name').onclick=()=>{clearActiveName();portal()};bindHostEntry()}
async function kioskPortal(d){const names=FIXED_PEOPLE,active=getName();if(active&&!names.includes(active)){clearActiveName();return kioskPortal(d)}if(!active){A.innerHTML=brand(`<span class="room">1 Handy</span>`)+`<section class="card hero"><div class="ey">Gemeinsames Handy</div><h2>Wer ist dran?</h2><p class="muted">Tippt auf euren Namen. Antworten und Ergebnisse bleiben getrennt.</p><div class="grid two">${names.map(n=>`<button class="choice" data-person="${e(n)}">${e(n)}</button>`).join('')}</div><button id="hostbutton" class="linkbtn hostexit">⚙️ Host-Steuerung</button></section>`;document.querySelectorAll('[data-person]').forEach(x=>x.onclick=()=>{setActiveName(x.dataset.person);portal()});hostbutton.onclick=()=>hostGate();return}if(eventTab()==='stand'){try{return renderEventHub(await loadEventOverview(),active,true)}catch(x){return xRoom(x.message||'Abendstand konnte nicht geladen werden')}}if(eventTab()==='host')return participantHostPortal(d);A.innerHTML=brand(`<span class="room">${e(active)}</span>`)+eventTabs('tastings')+`<section class="card hero"><h2>${e(active)} ist dran</h2><button id="switchperson" class="btn secondary full">👤 Teilnehmer wechseln</button></section><div class="pairlist">${d.rooms.map(pairCard).join('')}</div>${hostEntry()}`;switchperson.onclick=()=>{clearActiveName();portal()};bindHostEntry()}

// Host-Steuerung: PIN-Gate direkt in der App. Der Host-Token wird nie ausgeliefert,
// sondern einmalig eingesetzt und nur auf dem Gerät des Hosts gespeichert.
function hostEntry(){return `<div class="hostrow"><button id="hostbutton" class="linkbtn hostexit">⚙️ Host-Steuerung</button></div>`}
function bindHostEntry(){const b=document.getElementById('hostbutton');if(b)b.onclick=()=>hostGate()}
function hostGate(step='pin'){
  clearPoll();
  const wantToken=step==='token',back=`?event=${encodeURIComponent(E)}${KIOSK?'&kiosk=1':''}`;
  A.innerHTML=brand(`<span class="room">Host</span>`)+`<div class="toprow"><a class="backlink" href="${back}" data-nav="${back}">← Zurück zum Abend</a></div><section class="card hostgate"><div class="ey">⚙️ Geschützter Bereich</div><h2>Host-Steuerung</h2><p class="muted small">${wantToken?'PIN erkannt. Jetzt einmalig den Host-Token für diesen Abend einsetzen – er bleibt nur auf diesem Gerät gespeichert.':'Hier gibt der Host Profile und Auflösungen frei. Bitte den Host-PIN eingeben.'}</p><div class="field"><label for="hostinput">${wantToken?'Host-Token':'Host-PIN'}</label><input id="hostinput" type="password" autocomplete="off" ${wantToken?'placeholder="Token einsetzen"':'inputmode="numeric" maxlength="8" placeholder="••••"'}></div><button id="hostgo" class="btn primary full">${wantToken?'Host-Steuerung öffnen':'Weiter'}</button>${wantToken&&readHostToken()?`<button id="hostforget" class="linkbtn danger">Gespeicherten Token löschen</button>`:''}</section>`;
  const input=document.getElementById('hostinput'),go=document.getElementById('hostgo');
  const submit=()=>{
    const v=(input.value||'').trim();
    if(!v)return toast(wantToken?'Bitte den Host-Token einsetzen':'Bitte den Host-PIN eingeben');
    if(wantToken)return hostUnlock(v,go);
    if(!HOST_PINS.includes(v)){input.value='';input.focus();return toast('Falscher Host-PIN')}
    const stored=readHostToken();
    return stored?hostUnlock(stored,go):hostGate('token');
  };
  go.onclick=submit;
  input.onkeydown=x=>{if(x.key==='Enter')submit()};
  input.focus();
  const forget=document.getElementById('hostforget');
  if(forget)forget.onclick=()=>{clearHostToken();toast('Token gelöscht');hostGate('token')};
}
async function hostUnlock(token,btn){
  if(btn)btn.disabled=true;
  try{
    await rpc('host_get_event_state',{p_event_code:E,p_host_token:token});
    storeHostToken(token);
    location.href=`?event=${encodeURIComponent(E)}&hostmode=1`;
  }catch(x){
    if(btn)btn.disabled=false;
    clearHostToken();
    toast(x?.message||'Host-Token ungültig');
    hostGate('token');
  }
}
async function hostPortal(){
  clearPoll();
  if(!H)return hostGate();
  let h;
  try{h=await rpc('host_get_event_state',{p_event_code:E,p_host_token:H})}
  catch(x){clearHostToken();toast(x?.message||'Host-Token ungültig');return hostGate('token')}
  const exit=`?event=${encodeURIComponent(E)}`;
  A.innerHTML=brand(`<span class="room">Host</span>`)+`<section class="card hero"><div class="ey">⚙️ Host-Steuerung</div><h2>${e(h.title)}</h2><p class="muted small">Freigaben gelten sofort für alle Teilnehmer.</p><a class="btn secondary full center" href="?event=${encodeURIComponent(E)}&kiosk=1">📱 Zur Personenauswahl</a></section><div class="pairlist">${h.rooms.map(hostCard).join('')}</div><section class="card hostfooter"><a class="backlink" href="${exit}" data-nav="${exit}">← Host-Modus verlassen</a><button id="hostforget" class="linkbtn danger">Host-Token von diesem Gerät löschen</button></section>`;
  document.querySelectorAll('[data-phase]').forEach(x=>x.onclick=async()=>{
    const phase=x.dataset.phase,room=x.dataset.room;
    if(!confirm(phase==='profiles'?'Profile freigeben?':'Jetzt auflösen?'))return;
    clearPoll();x.disabled=true;
    try{await rpcCompat('host_set_room_phase_v2','host_set_room_phase',{p_event_code:E,p_host_token:H,p_room_code:room,p_phase:phase});hostPortal()}
    catch(err){x.disabled=false;toast(err?.message||'Freigabe fehlgeschlagen');poll=setTimeout(hostPortal,5000)}
  });
  const forget=document.getElementById('hostforget');
  if(forget)forget.onclick=()=>{clearHostToken();location.href=exit};
  poll=setTimeout(hostPortal,5000);
}

boot();
